name: 'Welcome'

on:
  fork:
  push:
    branches: [main]
  issues:
    types: [opened]
  pull_request_target:
    types: [opened]

jobs:
  welcome:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: EddieHubCommunity/gh-action-community/src/welcome@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: "Hello, @${{ github.actor }}! Your issue is the catalyst for innovation. We're excited to tackle it together and collaborate on finding a solution."
          pr-message: 'Well done, @${{ github.actor }}! 🎉 Thank you for initiating a pull request. Your contribution is invaluable, and we truly appreciate your efforts to enhance our project.'
          footer: 'The maintainers/owner will review it shortly and provide you with feedback and suggestions.'
